import { DefaultLayout } from "@/components";
import { Button } from "@chakra-ui/react";
import Head from "next/head";
import { signIn, signOut } from "next-auth/react";

export default function AuthSigninPage() {
  return (
    <>
      <Head>
        <title>Winton - Signin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Button
          colorScheme="blackAlpha"
          onClick={() => {
            signIn();
          }}
        >
          Github Login
        </Button>
        <Button
          colorScheme="blackAlpha"
          onClick={() => {
            signOut();
          }}
        >
          Github Logout
        </Button>
      </DefaultLayout>
    </>
  );
}
