import { DefaultLayout } from "@/components";
import { useState } from "react";
import Head from "next/head";
import {
  Center,
  Text,
  Box,
  Flex,
  Input,
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Select,
  Button,
  Heading,
} from "@chakra-ui/react";
import React from "react";
import next from "next";

export default function AuthSignupPage() {
  return (
    <>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Flex direction="column" borderWidth={2} borderColor="grey.100" p={3}>
          <Heading size="md" p="2" textAlign={"center"}>
            회원가입
          </Heading>
          <FormControl isRequired w="400px" m="3">
            <FormLabel>Email address</FormLabel>
            <Input type="email" placeholder="이메일 입력" />
            <FormLabel>password</FormLabel>
            <Input
              type="password"
              placeholder="6~12자 영문/대소문자, 숫자, 특수문자만 조합하여 입력"
            />
            <FormLabel>이름</FormLabel>
            <Input type="text" />
            <FormLabel>생년월일</FormLabel>
            <Input type="text" placeholder="19950120" />
            <FormLabel>휴대폰번호</FormLabel>
            <Input type="text" placeholder="1023231232" />
            <FormLabel>소속 시/도</FormLabel>
            <Select placeholder="부산">
              <option>서울</option>
              <option>부산</option>
              <option>대구</option>
              <option>인천</option>
              <option>광주</option>
              <option>대전</option>
              <option>울산</option>
              <option>세종</option>
              <option>경기</option>
              <option>강원</option>
              <option>충북</option>
              <option>전북</option>
              <option>전남</option>
              <option>경북</option>
              <option>경남</option>
              <option>제주</option>
            </Select>
            <FormLabel>소속 클럽</FormLabel>
            <Input type="text" placeholder="이지스클럽" />
          </FormControl>
          <Center>
            <Button p="3" w="50%" size="md" colorScheme="blackAlpha">
              Create a account
            </Button>
          </Center>
        </Flex>
      </DefaultLayout>
    </>
  );
}
