import { ContentContainer, DefaultLayout } from "@/components";
import { Image } from "@chakra-ui/react";
import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Winton - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <ContentContainer>
          <Image objectFit="cover" src="/winton.png" alt="없음" />
        </ContentContainer>
      </DefaultLayout>
    </>
  );
}
