import { DefaultLayout } from "@/components";
import { Button } from "@chakra-ui/react";
import Head from "next/head";

export default function CompetitionList() {
  return (
    <>
      <Head>
        <title>Winton - Competition List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Button size={"sm"} colorScheme={"red"}>
          Hi
        </Button>
      </DefaultLayout>
    </>
  );
}
