import { DefaultLayout } from "@/components";
import Head from "next/head";

export default function PlayerList() {
  return (
    <>
      <Head>
        <title>Winton - Player List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>PlayerListPage</DefaultLayout>
    </>
  );
}
